[package]
name = "titm"
version = "0.1.0"
authors = ["Joanna Doyle <jjadoyle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nix = "0.19"
termion = "1"
terminal-emulator = "0.1"
