[package]
name = "rusty-scum"
version = "0.1.0"
authors = ["Joanna Doyle <jjadoyle@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "0.3", features = ["full"] }
bytes = "0.6"
